name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check formatting
        run: bun prettier --check --ignore-unknown .
